sudo: false
language: php

sudo: false

php:
    - 5.4


install: gem install mysql2

script:
    -  pwd
    -  ls
    - ./fixtures/bin/fixtures "populate-schema",
    - ./fixtures/bin/fixtures "populate-triggers",
    - ./fixtures/bin/fixtures "populate-sprocs",
    - ./fixtures/bin/fixtures "populate-data",
    - ./fixtures/bin/fixtures "apply-transformations",
    - ./fixtures/bin/fixtures "install-enable",

notifications:
    email: false

source_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdTVUYmpsa3QyNGZvYkxNNUo2ajVoU2pvWVhaVU9YMjkreHEyWjcxVkpSWWN0MlB1Cmo4QkIzSEJ3T1o4bmNXZUdoT1ZtdUpSNVlKazJaWlpqcFVoN0tnVm9yUTV3UENDNjBzUUV0dE5SVTJwWG9qZUgKT0VDS1FLVE90V05DejNKajBnMlFWYkNwQnh3ZjdQQ1RubDNLWHFOODlqclFhZ20zRmJCTGM3alEzNXlYY0NIVQpIcGQ2NG1TNm1paTNzRVlCVlpxS0xBZGE3U3o4Wlh3R1NhWVNseDREVk1tNWpDN1lLbTNPRHRmaWxxQmorQXJZCjlKSWpGNmtJZUIyYm51bi95T2J2S29FYUw0UFpBZ2lHZlg4cnZOYjArdjRNaklnbENCUWMzYVYwbE9TVXk2YWoKSjZFWSs0Qk84NU5PK3V4cnRGOTdEbk14aDFMdmJvM0xrLzg5NHdJREFRQUJBb0lCQUYzaGdvRWI0UGVlYlpUNQpuZ0ZiY0laVWt2azBYN0xtVzg3dzc1bThDSUVuTC9nWTY2ekdiREFIbGlOQXBGejlreld3R2xrRzlqaUNkZGNpCkRYMExhWmorWEFWQTFLdEROajJHSFZYakxUQ3lhR21ub09WbVo4c3lzTUhYaS9pSEo2NVpXNE9IaHhFbjRsS1QKbFU0Tll0czZ0N0FFZjRxU2tpOG9ySnFlUk91a2VETjV5YmRqTDkzbk10dUZ0dDJQTTBybGlrcnNsWWRjMFBrcQozalpWc1VNRHhqZk1WNndXNE03UXFnWjl0bmJjcE9XbUVOTGlsKzVkMTdqSTFmS0ZianAvN29RckRYVTM0cmlUClhWR2tDd2xKd1d6bVFOeC9jWUpLU2R2ckx1QlJrWlB4bFdUQ09wa0l6TXNJRnQ3VVBLSDkrcjQ0VUtxemtSVUwKd29nU2R3RUNnWUVBNGRBcEhIVUM0RDkwaTBhL0pJcUlob3NST1RrTTFyS3N0QVFzRGk4RmpwTWJ3dHFjMzB0eAp0NW5BZ3YrYzVFYnlsYXQxOUVoYUgwejFUWVJWd1h4S0VlWHhkcUttVnVQVFp2QzhkMnZ1REc1NWFGTWg1Q3NiCm53Qmx1RitKR2FUT21sSnFxdlRrb0RpTmxaWThOSzk1V2VOQmNKd05yN3pIbnJrbHBCNm9PUmNDZ1lFQTFLaFMKcHN0eVZMSStPa3M2ZWlWeGJCb0R4L1JNYnRmME9yakNiTHNRbU0xbDFSM2V6dEs3aHl1am04eThKQjBVUFN4SApDekN3RUNXeGIxbHRVMDJlYk1OaEM1cmkzZ1Iza0dqS0E4cGdNaTc3ejZuTVVOSFAwVEZzWExPazR6Y0RXMVgrCmRPYmdNUjVWRlI2OC9RVHVmQW9ha2RnbDgrZjdmUmtWalBSTlNSVUNnWUJIeEozY1VvQVlmM0p0OVkwNGN1TVQKUjgyd2p5WTZjazBiWlp3TzRmajFLR0lSV3VPeXdFcWpITFduck0vVGFZMGQ3b0d0b3ZVcHI0N2pGU1VnT24xYwpGT1hhVzdWY05rcHhGQ0FDSUlabTR4R3BDNHJnOXFadnNYT2kxcEkvV1Ria3F6OEZtSkcxTG1RcFg3ZEEwMmhSCkhqNGxLU1BjYjdaT0J2QWtxaTJ5L3dLQmdRQy8yRll2K092Y3NxeG14SVV0dW1lM1lVUzE5NU9ZajZQWjhlSWMKV3lvZTMzV1ZySXZidzhxL3A4UENneEhiOW92U29BWTdkeUh1ZjBLeU5GZm5SZWU5TVFsMGdiZFhHV3FQMGFrbApnRVlHSDlLMXhmWDNsMEJHOWJKUGN4VTJrZU9xVzByaVJZSk5iWkxPS2R2TzJzc1hCYnB3aGpHKzl6SXU2aGxCCi93ZFYvUUtCZ0ZueGE5TDFlcW5tbHNScWpkcFFxcVcwM3F5VkUrSmpDR3g5R09SdjlvYnB0OHIxd2dYUktwY2gKZ2tWYms4aGpkQ3YvQnY5b0NSWDlMSTI1RGJRd3NIVTU4Nll0UzdHMjA4ckVFTkpReUNPNVd1ZkNUUWZkaHJRYwpsQ3NOR00rOUczMWptTEIzcGhpdThwc04zNVZYR3lkT1lmb3BDbW9lc2xWUVBuRGcrRzM1Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
