
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `events`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `events` (
  `event_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` int(10) unsigned DEFAULT NULL,
  `priority` tinyint(3) unsigned DEFAULT NULL,
  `brand_id` int(10) unsigned DEFAULT NULL,
  `code` varchar(32) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `title` varchar(100) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `url` varchar(255) NOT NULL DEFAULT '',
  `notes` text NOT NULL,
  `event_type` varchar(20) NOT NULL DEFAULT 'post_event',
  `private` tinyint(1) NOT NULL DEFAULT '0',
  `private_indicator` tinyint(1) NOT NULL DEFAULT '0',
  `private_event_note` varchar(300) DEFAULT '',
  `split` decimal(10,2) NOT NULL DEFAULT '70.00',
  `r_holdback` tinyint(2) DEFAULT '25',
  `zoom` tinyint(1) unsigned DEFAULT '1',
  `viewable_date` datetime DEFAULT NULL,
  `start_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `end_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `event_status` tinyint(3) unsigned NOT NULL DEFAULT '25',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `event_modified_date` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `delivery_low_day` int(10) unsigned DEFAULT '10',
  `delivery_high_day` int(10) unsigned DEFAULT '14',
  `delivery_canadian_offset` int(10) unsigned DEFAULT '3',
  `delivery_estimate_rule` enum('Business','Calendar') DEFAULT NULL,
  `event_delivery_date` date NOT NULL DEFAULT '0000-00-00',
  `first_payment` float(10,2) NOT NULL DEFAULT '0.00',
  `event_cap` int(10) unsigned NOT NULL DEFAULT '6',
  `handlingfee` decimal(4,2) NOT NULL DEFAULT '0.00',
  `agent` varchar(50) CHARACTER SET utf8 NOT NULL,
  `commission` decimal(10,2) NOT NULL DEFAULT '0.00',
  `group_by_style` tinyint(1) NOT NULL DEFAULT '0',
  `adjustment` float(10,2) NOT NULL,
  `adjustment_notes` text CHARACTER SET utf8 NOT NULL,
  `short_ship` decimal(4,2) NOT NULL DEFAULT '20.00',
  `short_ship_brand` decimal(4,2) NOT NULL DEFAULT '25.00',
  `description` text CHARACTER SET utf8 NOT NULL,
  `tagline` varchar(55) NOT NULL DEFAULT '',
  `finalsale` tinyint(1) NOT NULL DEFAULT '0',
  `region` enum('west','east') NOT NULL DEFAULT 'west',
  `sort_order` int(11) NOT NULL DEFAULT '99',
  `received_date` datetime DEFAULT NULL,
  `hl_default_sale_type` enum('default','select') CHARACTER SET utf8 NOT NULL DEFAULT 'default',
  `display_brand_name` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `return_to` varchar(20) NOT NULL DEFAULT 'brand',
  `vertical` varchar(30) DEFAULT NULL,
  `department` varchar(30) DEFAULT NULL,
  `category` varchar(30) DEFAULT NULL,
  `opp_id` int(10) unsigned DEFAULT NULL,
  `event_rating` tinyint(3) unsigned DEFAULT '1' COMMENT 'rating 1 to 5 will be DEPRECATED replaced by event_type',
  `event_class` varchar(20) NOT NULL DEFAULT 'Branded',
  `event_platform` varchar(20) NOT NULL DEFAULT 'HL Email',
  `discount_range` varchar(45) DEFAULT NULL COMMENT 'ex 0-0',
  `price_range` varchar(45) DEFAULT NULL COMMENT 'ex 0-0',
  `no_skus` int(10) unsigned DEFAULT '0',
  `hazard_material` enum('Y','N') NOT NULL DEFAULT 'N',
  `studio` enum('Y','N') NOT NULL DEFAULT 'N',
  `models` enum('Y','N') NOT NULL DEFAULT 'N',
  `image_sent` enum('Y','N') NOT NULL DEFAULT 'N',
  `factor_style` tinyint(3) unsigned DEFAULT '1' COMMENT '1 to 5',
  `factor_color` tinyint(3) unsigned DEFAULT '1',
  `factor_size` tinyint(3) unsigned DEFAULT '1',
  `ots_initial` decimal(11,2) DEFAULT '0.00',
  `ots_final` decimal(11,2) DEFAULT '0.00',
  `sales_projection_initial` decimal(11,2) DEFAULT '0.00',
  `sales_projection_final` decimal(11,2) DEFAULT '0.00',
  `sales_associate` varchar(30) DEFAULT NULL,
  `oversized` enum('Y','N') NOT NULL DEFAULT 'N',
  `drop_ship` enum('Y','N') NOT NULL DEFAULT 'N' COMMENT 'will be DEPRECATED replaced by event_type',
  `gift_with_purchase` enum('Y','N') NOT NULL DEFAULT 'N',
  `rma_required` enum('Y','N') NOT NULL DEFAULT 'Y',
  `prepaid_percentage` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `first_payment_percentage` tinyint(3) unsigned NOT NULL DEFAULT '75',
  `first_payment_timing` tinyint(3) unsigned NOT NULL DEFAULT '10' COMMENT 'days',
  `net_payment_percentage` tinyint(3) unsigned NOT NULL DEFAULT '25',
  `net_payment_timing` tinyint(3) unsigned NOT NULL DEFAULT '35' COMMENT 'days',
  `supplier` varchar(15) DEFAULT NULL,
  `msa_group` varchar(100) NOT NULL DEFAULT '',
  `shipping_calc_rule` varchar(50) NOT NULL DEFAULT 'weight',
  `price_visible` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `discount_visible` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `preview_minutes` int(10) unsigned NOT NULL DEFAULT '15',
  `coa` varchar(50) DEFAULT NULL,
  `built_in_freight` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `carrier` varchar(20) NOT NULL DEFAULT 'UPS',
  `event_display_format` varchar(25) NOT NULL DEFAULT 'Regular',
  `affinity` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `nordstrom_transfer` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `email_purchase_order_to` varchar(100) NOT NULL DEFAULT '',
  `first_received_in_warehouse_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `show_event_title` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT 'display the event title on the tile?',
  `hero_title_display_format` varchar(20) NOT NULL DEFAULT 'text-blue',
  `is_afternoon_event` tinyint(1) NOT NULL DEFAULT '0',
  `is_case_pack_purchase` tinyint(1) NOT NULL DEFAULT '0',
  `is_high_priority` tinyint(1) NOT NULL DEFAULT '0',
  `production_due_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `primary_production_source` varchar(30) DEFAULT NULL,
  `production_approval_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`event_id`),
  UNIQUE KEY `priority` (`priority`,`parent_id`),
  KEY `end_date` (`end_date`),
  KEY `createDate` (`create_date`),
  KEY `received_date` (`received_date`),
  KEY `FK_events::verticals` (`vertical`),
  KEY `FK_events::departments` (`department`),
  KEY `FK_events::categories` (`category`),
  KEY `FK_events::sales_associates` (`sales_associate`),
  KEY `FK_events::brands` (`brand_id`),
  KEY `FK_events::suppliers` (`supplier`),
  KEY `code` (`code`),
  KEY `FK_events::event_statuses` (`event_status`),
  KEY `FK_events::events` (`parent_id`),
  KEY `FK_events::delivery_estimates` (`delivery_low_day`,`delivery_high_day`,`delivery_estimate_rule`),
  KEY `idx1` (`event_status`,`start_date`,`end_date`),
  KEY `code_2` (`code`),
  KEY `event_id` (`event_id`,`event_type`,`region`),
  KEY `FK_events::shipping_calc_rules` (`shipping_calc_rule`),
  KEY `start_date_2` (`start_date`,`event_status`,`brand_id`,`event_id`),
  KEY `FK_events::category_of_activity` (`coa`),
  KEY `end_date_2` (`end_date`),
  KEY `brand_id` (`brand_id`,`event_id`),
  KEY `event_type` (`event_type`,`start_date`,`event_status`,`event_id`),
  KEY `FK_events::carriers` (`carrier`),
  KEY `FK_events::event_display_formats` (`event_display_format`),
  KEY `sort_order` (`sort_order`,`event_id`),
  KEY `FK_events::return_tos` (`return_to`),
  KEY `FK_events::hero_title_display_format` (`hero_title_display_format`),
  KEY `primary_production_source` (`primary_production_source`),
  KEY `FK_events::event_class` (`event_class`),
  KEY `FK_events::event_platform` (`event_platform`),
  CONSTRAINT `FK_events::brands` FOREIGN KEY (`brand_id`) REFERENCES `brands` (`brand_id`) ON UPDATE CASCADE,
  CONSTRAINT `FK_events::carriers` FOREIGN KEY (`carrier`) REFERENCES `carriers` (`carrier`) ON UPDATE CASCADE,
  CONSTRAINT `FK_events::categories` FOREIGN KEY (`category`) REFERENCES `categories` (`category`) ON UPDATE CASCADE,
  CONSTRAINT `FK_events::category_of_activity` FOREIGN KEY (`coa`) REFERENCES `category_of_activity` (`coa`) ON UPDATE CASCADE,
  CONSTRAINT `FK_events::delivery_estimates` FOREIGN KEY (`delivery_low_day`, `delivery_high_day`, `delivery_estimate_rule`) REFERENCES `delivery_estimates` (`delivery_low_day`, `delivery_high_day`, `delivery_estimate_rule`) ON UPDATE CASCADE,
  CONSTRAINT `FK_events::departments` FOREIGN KEY (`department`) REFERENCES `departments` (`department`) ON UPDATE CASCADE,
  CONSTRAINT `FK_events::events` FOREIGN KEY (`parent_id`) REFERENCES `events` (`event_id`) ON UPDATE CASCADE,
  CONSTRAINT `FK_events::events_primary_production_sources` FOREIGN KEY (`primary_production_source`) REFERENCES `events_primary_production_sources` (`primary_production_source`) ON UPDATE CASCADE,
  CONSTRAINT `FK_events::event_class` FOREIGN KEY (`event_class`) REFERENCES `event_classes` (`event_class`) ON UPDATE CASCADE,
  CONSTRAINT `FK_events::event_display_formats` FOREIGN KEY (`event_display_format`) REFERENCES `event_display_formats` (`event_display_format`) ON UPDATE CASCADE,
  CONSTRAINT `FK_events::event_platform` FOREIGN KEY (`event_platform`) REFERENCES `event_platforms` (`event_platform`) ON UPDATE CASCADE,
  CONSTRAINT `FK_events::event_statuses` FOREIGN KEY (`event_status`) REFERENCES `event_statuses` (`event_status`) ON UPDATE CASCADE,
  CONSTRAINT `FK_events::event_types` FOREIGN KEY (`event_type`) REFERENCES `event_types` (`event_type`) ON UPDATE CASCADE,
  CONSTRAINT `FK_events::hero_title_display_format` FOREIGN KEY (`hero_title_display_format`) REFERENCES `title_display_formats` (`title_display_format`) ON UPDATE CASCADE,
  CONSTRAINT `FK_events::return_tos` FOREIGN KEY (`return_to`) REFERENCES `return_tos` (`return_to`),
  CONSTRAINT `FK_events::sales_associates` FOREIGN KEY (`sales_associate`) REFERENCES `sales_associates` (`sales_associate`) ON UPDATE CASCADE,
  CONSTRAINT `FK_events::shipping_calc_rules` FOREIGN KEY (`shipping_calc_rule`) REFERENCES `shipping_calc_rules` (`shipping_calc_rule`) ON UPDATE CASCADE,
  CONSTRAINT `FK_events::suppliers` FOREIGN KEY (`supplier`) REFERENCES `suppliers` (`supplier`),
  CONSTRAINT `FK_events::verticals` FOREIGN KEY (`vertical`) REFERENCES `verticals` (`vertical`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=38569 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

